[package]
name = "brainfast"
version = "0.1.0"
authors = ["Pietro Moro <pietromoro@programmer.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
